#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -line-padding 4 -columns 2 -padding 30 -hide-scrollbar -show-icons -drun-icon-theme "Papirus" -font "Mono 12" -theme-str 'window {width: 40%;}'
