#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 32 -xoffset -10 -theme-str 'window {width: 10%;} listview {lines: 5;}' -hide-scrollbar -font "Mono 12" <<< "Lock|Suspend|Logout|Reboot|Shutdown")"
    case "$MENU" in
        *Lock) i3lock-fancy ;;
        *Suspend) systemctl suspend ;;
        *Logout) i3-msg exit;;
        *Reboot) systemctl reboot ;;
        *Shutdown) systemctl -i poweroff
    esac
